[package]
name = "sunflowerecs"
version = "2.1.0"
edition = "2024"
description = "A hybrid ECS library written in Rust."
readme = "README.md"
license-file = "LICENSE"

[dependencies]
boxmut = "1.0.0"
